[package]
name = "ruky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
num = "0.4.1"
rand = "0.8.5"
thiserror = "1.0.56"
